name: CI

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  docker-build-push:
    runs-on: ubuntu-latest
    steps:
      - name: 'Pull Code'
        uses: actions/checkout@v4
      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}        
      - name: 'Build Inventory Image'
        run: |
          repo=$(echo $GITHUB_REPOSITORY_OWNER | tr '[:upper:]' '[:lower:]')
          docker build . --tag ghcr.io/$c/downdetector-exporter:latest
          docker push ghcr.io/$GITHUB_REPOSITORY_OWNER/downdetector-exporter:latest
