name: CI

on:
  push:
    branches: [ master, dockerfile ]
  pull_request:

jobs:
  docker-build-push:
    runs-on: ubuntu-latest
    steps:
      - name: 'Pull Code'
        uses: actions/checkout@main
      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@main
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}        
      - name: 'Build Inventory Image'
        run: |
          docker build . --tag ghcr.io/nohn/downdetector-exporter:latest
          docker push ghcr.io/nohn/downdetector-exporter:latest
